### ISSUE TITLE
Micro "Not capturing exception because it's already been captured"

### ISSUE THREAD

**Issue by amccloud** [realkosty/sentry-micro-frontend#1]
Thanks for taking the time to setup this solid test harness. Really looking forward to first-class support.

I've cloned locally to try things out with my own DSN. Almost all seem to work as expected. I'm not seeing micro exceptions anywhere in the micro or host project. I am seeing a single session attributed to the micro DSN, so it appears to load the micro DSN client correctly.

#### Settings
- flex-micro | simple-remote | simple-lib
- SDK: 7.29.0/bundle.tracing.js
- Host: sentry, tracing, debug
- Micro: sentry, tracing
- Chrome: 109.0.5414.87
- Adblock: Disabled

To add to that. It seems there is no debug output or micro exceptions captured with these settings:
- Host: sentry, tracing
- Micro: sentry, tracing, debug

#### Host Logs
```
Sentry Logger [log]: Not capturing exception because it's already been captured.
helpers.js:112 Uncaught Error: Uncaught exception in event handler added by [MICRO]
    at eventhandler_callback (micro.js:49:15)
    at HTMLButtonElement.<anonymous> (common.js:205:5)
    at HTMLButtonElement.<anonymous> (flex-micro.js:161:20)
    at HTMLButtonElement.sentryWrapped (helpers.js:90:1)
```
#### Micro Logs
Works as expected when Host sentry is disabled.

**Comment by amccloud** [comment]
I suspect maybe the original warning I documented is a false flag. I just tried with the following micro-only settings and I'm setting not seeing micro exceptions for any DSN:
- Host: n/a
- Micro: sentry, tracing, debug

```
logger.js:60 Sentry Logger [warn]: SentryError: Event processing pipeline threw an error, original event will not be sent. Details have been sent as a new event.
Reason: TypeError: Cannot read properties of undefined (reading 'map')

flex-micro.js:165 Uncaught Error: Uncaught exception in event handler added by [MICRO]
    at eventhandler_callback (micro.js:49:15)
    at HTMLButtonElement.<anonymous> (common.js:205:5)
    at HTMLButtonElement.<anonymous> (flex-micro.js:161:20)
eventhandler_callback @ micro.js:49
(anonymous) @ common.js:205
(anonymous) @ flex-micro.js:161

logger.js:60 Sentry Logger [log]: No outcomes to send
```

I'm seeing this error reported to both DSN so I think this is likely the root issue. Stack from Sentry host:

```
TypeError: Cannot read properties of undefined (reading 'map')
  at prepareEvent(../../../core/build/esm/utils/prepareEvent.js:37:1)
  at BaseClient._prepareEvent(../../../core/build/esm/baseclient.js:389:1)
  at BrowserClient._prepareEvent(../../../browser/build/npm/esm/client.js:91:1)
  at BaseClient._processEvent(../../../core/build/esm/baseclient.js:458:1)
  at BaseClient._captureEvent(../../../core/build/esm/baseclient.js:399:1)
  at BaseClient.captureEvent(../../../core/build/esm/baseclient.js:142:1)
  at beforeSend(/methods/simple-lib.js:48:50)
  at processBeforeSend(../../../core/build/esm/baseclient.js:615:1)
  at <anonymous>(../../../core/build/esm/baseclient.js:470:1)
  at Array.<anonymous>(../../../utils/build/esm/syncpromise.js:74:1)
  at <anonymous>(../../../utils/build/esm/syncpromise.js:178:1)
  at Array.forEach(<anonymous>)
  at this._executeHandlers(../../../utils/build/esm/syncpromise.js:171:1)
  at <anonymous>(../../../utils/build/esm/syncpromise.js:92:1)
  at new SyncPromise(../../../utils/build/esm/syncpromise.js:53:1)
  at SyncPromise.then(../../../utils/build/esm/syncpromise.js:64:1)
  at BaseClient._processEvent(../../../core/build/esm/baseclient.js:459:1)
  at BaseClient._captureEvent(../../../core/build/esm/baseclient.js:399:1)
  at <anonymous>(../../../core/build/esm/baseclient.js:93:1)
  at Array.<anonymous>(../../../utils/build/esm/syncpromise.js:74:1)
  at <anonymous>(../../../utils/build/esm/syncpromise.js:178:1)
  at Array.forEach(<anonymous>)
  at this._executeHandlers(../../../utils/build/esm/syncpromise.js:171:1)
  at <anonymous>(../../../utils/build/esm/syncpromise.js:92:1)
  at new SyncPromise(../../../utils/build/esm/syncpromise.js:53:1)
  at SyncPromise.then(../../../utils/build/esm/syncpromise.js:64:1)
  at BaseClient.captureException(../../../core/build/esm/baseclient.js:93:1)
  at <anonymous>(../../../core/build/esm/hub.js:131:1)
  at Hub._withClient(../../../core/build/esm/hub.js:416:1)
  at Hub.captureException(../../../core/build/esm/hub.js:130:1)
  at captureException(../../../core/build/esm/exports.js:19:1)
  at <anonymous>(../../../browser/build/npm/esm/helpers.js:109:1)
  at Hub.withScope(../../../core/build/esm/hub.js:95:1)
  at withScope(../../../core/build/esm/exports.js:141:1)
```

**Comment by amccloud** [comment]
Root is was missing integrations option for micro clients.

**Comment by realkosty** [comment]
Thanks for documenting this
I've updated all methods https://github.com/realkosty/sentry-micro-frontend/commit/649a2b93b74d8501e4af1bc6041fc7a5546f307b
and also submitted a grievance about breaking changes https://github.com/getsentry/sentry-javascript/issues/7153 (feel free to upvote/comment)
Also FYI, there was another thing breaking with latest, v7.37.1, that one can't blame on anyone since I used private `BrowserClient._options` previously. It's fixed now as well https://github.com/realkosty/sentry-micro-frontend/commit/0bd7608fae354e2c8692c01a0b362b568cbecf8d
